### ISSUE TITLE
Failed test case

### ISSUE THREAD

**Issue by paranoidjk** [react-component/tree-select#62]
https://github.com/react-component/tree-select/blob/master/tests/Select.multiple.spec.js#L72

**Comment by yesmeck** [comment]
https://travis-ci.org/react-component/tree-select/builds/235187244

没问题啊。

**Comment by paranoidjk** [comment]
```bash
yarn test v0.27.5
$ jest
 FAIL  tests/Select.multiple.spec.js
  ● TreeSelect.multiple › remove by backspace key twice when treeCheckable and under controlled

    expect(received).toHaveLength(length)

    Expected value to have length:
      1
    Received:
      {"complexSelector": {"buildPredicate": [Function buildInstPredicate], "childrenOfNode": [Function childrenOfInst], "findWhereUnwrapped": [Function findWhereUnwrapped]}, "component": null, "length": 0, "node": undefined, "nodes": Array [], "options": {}, "root": {"complexSelector": {"buildPredicate": [Function buildInstPredicate], "childrenOfNode": [Function childrenOfInst], "findWhereUnwrapped": [Function findWhereUnwrapped]}, "component": {"_reactInternalInstance": {"_calledComponentWillUnmount": false, "_compositeType": 0, "_context": {}, "_currentElement": {"$$typeof": Symbol(react.element), "_owner": null, "_store": [Object], "key": null, "props": [Object], "ref": null, "type": [Function WrapperComponent]}, "_debugID": 74, "_hostContainerInfo": {"_ancestorInfo": [Object], "_idCounter": 14, "_namespaceURI": "http://www.w3.org/1999/xhtml", "_node": [Object], "_ownerDocument": [Object], "_tag": "div", "_topLevelWrapper": [Object]}, "_hostParent": null, "_instance": [Circular], "_mountImage": null, "_mountIndex": 0, "_mountOrder": 28, "_pendingCallbacks": null, "_pendingElement": null, "_pendingForceUpdate": false, "_pendingReplaceState": false, "_pendingStateQueue": null, "_renderedComponent": {"_calledComponentWillUnmount": false, "_compositeType": 0, "_context": [Object], "_currentElement": [Object], "_debugID": 75, "_hostContainerInfo": [Object], "_hostParent": null, "_instance": [Object], "_mountImage": null, "_mountIndex": 0, "_mountOrder": 29, "_pendingCallbacks": null, "_pendingElement": null, "_pendingForceUpdate": false, "_pendingReplaceState": false, "_pendingStateQueue": null, "_renderedComponent": [Object], "_renderedNodeType": 1, "_rootNodeID": 0, "_topLevelWrapper": null, "_updateBatchNumber": null, "_warnedAboutRefsInRender": false}, "_renderedNodeType": 1, "_rootNodeID": 0, "_topLevelWrapper": {"_calledComponentWillUnmount": false, "_compositeType": 0, "_context": [Object], "_currentElement": [Object], "_debugID": 0, "_hostContainerInfo": [Object], "_hostParent": null, "_instance": [Object], "_mountImage": null, "_mountIndex": 0, "_mountOrder": 27, "_pendingCallbacks": null, "_pendingElement": null, "_pendingForceUpdate": false, "_pendingReplaceState": false, "_pendingStateQueue": null, "_renderedComponent": [Circular], "_renderedNodeType": 1, "_rootNodeID": 0, "_topLevelWrapper": null, "_updateBatchNumber": null, "_warnedAboutRefsInRender": false}, "_updateBatchNumber": null, "_warnedAboutRefsInRender": false}, "context": {}, "props": {"Component": [Function App], "context": null, "props": {}}, "refs": {}, "state": {"context": null, "mount": true, "props": {}}, "updater": {"enqueueCallback": [Function enqueueCallback], "enqueueCallbackInternal": [Function enqueueCallbackInternal], "enqueueElementInternal": [Function enqueueElementInternal], "enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted], "validateCallback": [Function validateCallback]}}, "length": 1, "node": {"_reactInternalInstance": {"_calledComponentWillUnmount": false, "_compositeType": 0, "_context": {}, "_currentElement": {"$$typeof": Symbol(react.element), "_owner": [Object], "_store": [Object], "key": null, "props": [Object], "ref": null, "type": [Function App]}, "_debugID": 75, "_hostContainerInfo": {"_ancestorInfo": [Object], "_idCounter": 14, "_namespaceURI": "http://www.w3.org/1999/xhtml", "_node": [Object], "_ownerDocument": [Object], "_tag": "div", "_topLevelWrapper": [Object]}, "_hostParent": null, "_instance": [Circular], "_mountImage": null, "_mountIndex": 0, "_mountOrder": 29, "_pendingCallbacks": null, "_pendingElement": null, "_pendingForceUpdate": false, "_pendingReplaceState": false, "_pendingStateQueue": null, "_renderedComponent": {"_calledComponentWillUnmount": false, "_compositeType": 0, "_context": [Object], "_currentElement": [Object], "_debugID": 76, "_hostContainerInfo": [Object], "_hostParent": null, "_instance": [Object], "_mountImage": null, "_mountIndex": 0, "_mountOrder": 30, "_pendingCallbacks": null, "_pendingElement": null, "_pendingForceUpdate": false, "_pendingReplaceState": false, "_pendingStateQueue": null, "_renderedComponent": [Object], "_renderedNodeType": 1, "_rootNodeID": 0, "_topLevelWrapper": null, "_updateBatchNumber": null, "_warnedAboutRefsInRender": false}, "_renderedNodeType": 1, "_rootNodeID": 0, "_topLevelWrapper": null, "_updateBatchNumber": null, "_warnedAboutRefsInRender": false}, "context": {}, "handleChange": [Function anonymous], "props": {}, "refs": {}, "state": {"value": Array []}, "updater": {"enqueueCallback": [Function enqueueCallback], "enqueueCallbackInternal": [Function enqueueCallbackInternal], "enqueueElementInternal": [Function enqueueElementInternal], "enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted], "validateCallback": [Function validateCallback]}}, "nodes": [{"_reactInternalInstance": {"_calledComponentWillUnmount": false, "_compositeType": 0, "_context": [Object], "_currentElement": [Object], "_debugID": 75, "_hostContainerInfo": [Object], "_hostParent": null, "_instance": [Circular], "_mountImage": null, "_mountIndex": 0, "_mountOrder": 29, "_pendingCallbacks": null, "_pendingElement": null, "_pendingForceUpdate": false, "_pendingReplaceState": false, "_pendingStateQueue": null, "_renderedComponent": [Object], "_renderedNodeType": 1, "_rootNodeID": 0, "_topLevelWrapper": null, "_updateBatchNumber": null, "_warnedAboutRefsInRender": false}, "context": {}, "handleChange": [Function anonymous], "props": {}, "refs": {}, "state": {"value": Array []}, "updater": {"enqueueCallback": [Function enqueueCallback], "enqueueCallbackInternal": [Function enqueueCallbackInternal], "enqueueElementInternal": [Function enqueueElementInternal], "enqueueForceUpdate": [Function enqueueForceUpdate], "enqueueReplaceState": [Function enqueueReplaceState], "enqueueSetState": [Function enqueueSetState], "isMounted": [Function isMounted], "validateCallback": [Function validateCallback]}}], "options": {}, "root": [Circular]}}
    received.length:
      0

      at Object.<anonymous> (tests/Select.multiple.spec.js:76:20)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:753:12)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

 PASS  tests/Select.checkable.spec.js
 PASS  tests/Select.spec.js (5.212s)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 25 passed, 26 total
Snapshots:   7 passed, 7 total
Time:        6.218s
Ran all test suites.
error Command failed with exit code 1.
```

本机跑跑看看？

**Comment by yesmeck** [comment]
也好的呀。
